python pretrain.py \
    --gpus 1 \
    --save-dir ./save/CF-$(date +%b%d-%H-%M-%Y) \
    --max-seq-len 1200 \
    --batch-size 32 \
    --nlayers 6 \
    --nheads 8 \
    --embsize 256 \
    --d-hid 512 \
    --epochs 15 \
    --lr 0.0001 \
    --warmup-ratio-or-step 1 \
    --trunc-by-sample \
    --loss "mse" \
    --train-path "./DATA/brain/processed_data/train" \
    --zero-percentages 0.2 0.4 0.6 \
    --conditions "technology" \
    --balance-primary "tissue" \
    --balance-secondary "technology" \
    --strategy='auto' \
    --grad-accu-steps 1 \
    --seed 0 \
    --training-tasks "pcpt" \
    --do-dat \
    --do-mvc